#!/bin/bash

source utilities

function monitor_mode(){
    [[ $# -eq 0 ]] && return
    if [[ $1 == "on" ]]; then
	iw=`(iwconfig | awk '/wl/ {print $1}') 2>/dev/null` &&
	    iw=`menu 'Change to monitor mode:' "$iw"`
	if [[ "$(sudo ip link show up $iw)" == "" ]]; then
	    notify "Interface is disabled"
	    return
	else
	    notify &&
		sudo airmon-ng start "$iw" &&
		iw=`(iwconfig | awk '/wl/ {print $1}' | grep "$iw") 2>/dev/null` &&
		notify "Interface changed to $iw"
	fi
    elif [[ $1 == "off" ]]; then
	iw=`(iwconfig | awk '/wl/ {print $1}' | grep mon) 2>/dev/null` &&
	    iw=`menu 'Change to normal mode:' "$iw"` &&
	    sudo airmon-ng stop "$iw" &&
	    notify "Interface changed to $(echo $iw | sed 's/mon//g')"
    fi
}

function scan_network(){
    nmap -sn "$1" | grep "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$" | cut -d' ' -f5
}

function list_prots(){
    nmap -Pn "$1" | grep "^[0-9]"
}

