#!/bin/bash

###########################################################
#
# Smart Desk Control
#
# Written by Dimitri Tzika
#
# Synopsis: desk OPTION
#
# OPTIONS: backLight, monitor, light
# backLight: toggle backLight
# monitor: toggle monitor
# light: toggle light
#
# Examples:
# desk light
# desk monitor
# desk l
# desk bl
#
###########################################################

if [[ "$#" -ne 1 ]]; then
    echo "Too many arguments or none" 1>&2
    exit 1
else
    case "$1" in
	[rR] | [rR][aA][dD][iI][oO]) (curl 192.168.123.200 | grep -e '?comRelay1=on' && curl 192.168.123.200/?comRelay1=on || curl 192.168.123.200/?comRelay1=off) >/dev/null 2>/dev/null;;
	[mM] | [mM][oO][nN][iI][tT][oO][rR]) (curl 192.168.123.200 | grep -e '?comRelay2=on' && curl 192.168.123.200/?comRelay2=on || curl 192.168.123.200/?comRelay2=off) >/dev/null 2>/dev/null;;
	[lL] | [lL][iI][gG][hH][tT]) (curl 192.168.123.200 | grep -e '?comRelay3=on' && curl 192.168.123.200/?comRelay3=on || curl 192.168.123.200/?comRelay3=off) >/dev/null 2>/dev/null;;
	[bB][lL] | [bB][aA][cC][kK][lL][iI][gG][hH][tT]) (curl 192.168.123.200 | grep -e '?comRelay4=on' && curl 192.168.123.200/?comRelay4=on || curl 192.168.123.200/?comRelay4=off) >/dev/null 2>/dev/null;;
	*) echo "Not valid argument" 1>&2
	   exit 1;;
    esac
fi
