#!/bin/bash

###########################################################
#
# Dynamic Wallpaper
#
# Written by Dimitri Tzika
#
###########################################################

time="$(date +%H%M)"
if [ "$time" -lt 0230 ]; then
    pic=1
elif [ "$time" -lt 0400  ]; then
    pic=2
elif [ "$time" -lt 0530 ]; then
    pic=3
elif [ "$time" -lt 0700 ]; then
    pic=4
elif [ "$time" -lt 0830 ]; then
    pic=5
elif [ "$time" -lt 1000 ]; then
    pic=6
elif [ "$time" -lt 1130 ]; then
    pic=7
elif [ "$time" -lt 1300 ]; then
    pic=8
elif [ "$time" -lt 1430 ]; then
    pic=9
elif [ "$time" -lt 1600 ]; then
    pic=10
elif [ "$time" -lt 1730 ]; then
    pic=11
elif [ "$time" -lt 1900 ]; then
    pic=12
elif [ "$time" -lt 2030 ]; then
    pic=13
elif [ "$time" -lt 2200 ]; then
    pic=14
elif [ "$time" -lt 2330 ]; then
    pic=15
else
    pic=16
fi
DISPLAY=:0 feh --bg-scale "/home/dimitris/Pictures/Wallpapers/DynamicWallpapers/$pic.jpg"

