#!/bin/bash

user=~
wallpaper="hachioji"

feh --bg-scale "$user/Pictures/Wallpapers/DynamicWallpapers/$wallpaper/`date +%H | sed 's/^0//g'`.jpg"

if [[ `date +%H | sed 's/^0//g'` -ge 07 && `date +%H | sed 's/^0//g'` -le 20 ]]; then
    echo ""
else
    echo ""
fi
