#!/bin/bash

###########################################################
#
# Emojis
#
# Written by Dimitri Tzika
#
###########################################################

grep -v "#" ~/.emojis | dmenu -i -l 15 -fn Monospace-18 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
