#!/bin/bash

###########################################################
#
# Emojis
#
# Written by Dimitri Tzika
#
###########################################################

#Check if dmenu is running
pgrep -x dmenu && exit 1

grep -v "#" /usr/local/bin/.emojis | dmenu -i -l 15 -fn Monospace-18 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
