#!/bin/bash

###########################################################
#
# Lock
#
# Dependencies: i3lock-lixxia-git, scrot, ImageMagic
#
# Written by "https://www.reddit.com/r/unixporn/comments/3358vu/i3lock_unixpornworthy_lock_screen/"
#
# Synopsis: lock
#
# Examples:
# lock
#
###########################################################

# Play lock sound
(sleep 1.1 && mplayer "$HOME/.sounds/lock.wav") &

# Us keyboard layout and swap caps lock with escape
setxkbmap us && xmodmap -e 'clear Lock' && xmodmap -e 'keycode 0x42=Escape' && xmodmap -e 'keycode 0x9=Caps_Lock'

# Pixelate background
ICON="$HOME/Pictures/Wallpapers/icon.png"
TMPBG=/tmp/screen.png
scrot "$TMPBG"
convert "$TMPBG" -scale 10% -scale 1000% "$TMPBG"
convert "$TMPBG" "$ICON" -gravity center -composite -matte "$TMPBG"
i3lock -u -i "$TMPBG"
rm "$TMPBG"

# Play unlock sound
# Disaster!
while pgrep 'i3lock'; do
    sleep .5
done
mplayer "$HOME/.sounds/unlock.wav"
