#!/bin/bash

DATE=$(date +"%A, %B %-d")

ringcolor=FFFFFFFF
insidecolor=00000000
linecolor=00000000
separatorcolor=00000000

ringvercolor=00000000
insidevercolor=00000000

ringwrongcolor=00000000
insidewrongcolor=00000000

keyhlcolor=AAAAAAFF
bshlcolor=AAAAAAFF

# Us keyboard layout and swap caps lock with escape
setxkbmap us && xmodmap ~/.Xmodmap

# Pixelate background
#ICON="$HOME/Pictures/Wallpapers/icon2.png"
TMPBG=/tmp/screen.png
scrot "$TMPBG"
convert "$TMPBG" -scale 10% -scale 1000% "$TMPBG"
#convert "$TMPBG" "$ICON" -gravity center -composite -matte "$TMPBG"

i3lock -t -i "$TMPBG" \
    --clock --force-clock --timepos="w/2:h/2" --timesize=96 --timecolor=FFFFFFFF \
    --datestr="$DATE" --datepos="tx:ty+80" --datesize=32 --datecolor=FFFFFFFF \
    --indpos="w/2-r/2:h-r*2" --radius 20 \
    --ringcolor=$ringcolor --insidecolor=$insidecolor --linecolor=$linecolor \
    --separatorcolor=$separatorcolor --ringvercolor=$ringvercolor \
    --insidevercolor=$insidevercolor --veriftext='' --ringwrongcolor=$ringwrongcolor \
    --insidewrongcolor=$insidewrongcolor --wrongtext='' --keyhlcolor=$keyhlcolor \
    --bshlcolor=$bshlcolor --noinputtext='' \
    --screen=1

rm "$TMPBG"



