#!/bin/bash

#TODO make mpv use hd no full hd or higher

case $(printf 'Edit\nMode\nMusic\nLive' | dmenu -b -i -sb "#880000" -p "Which option?") in
	'Edit')
	sleep .2
	file=`find ~/.dotfiles/ThinkpadX200s -type f | grep -v emacs.d | dmenu -b -i -sb "#880000" -p "Select file:"` && (emacs $file & disown emacs);;
	'Mode')
	sleep .2
	case $(printf 'Home\nWork' | dmenu -b -i -sb "#880000" -p "Select mode:") in
	'Home')xrandr --output VGA-1 --primary --right-of LVDS-1 --auto && xrandr --output LVDS-1 --left-of VGA-1 --auto && xmonad --restart;;
	'Work')xrandr --output VGA-1 --above LVDS-1 --auto && xrandr --output LVDS-1 --primary --below VGA-1 --auto && xmonad --restart;;
	esac;;
    'Music')
	sleep .2
	option=$(cut -d ' ' -f2 ~/.youtube-videos | dmenu -b -i -sb "#880000" -p "Select music video?")
	mpv --ytdl-format=22 $(grep $option ~/.youtube-videos | cut -d ' ' -f1) &>/dev/null &;;
	'Live')
	sleep .2
	option=$(cut -d ' ' -f2 ~/.live-stream-videos | dmenu -b -i -sb "#880000" -p "Select live stream?")
	mpv $(grep $option ~/.live-stream-videos | cut -d ' ' -f1) &>/dev/null &;;
esac
