#!/bin/bash

source utilities

#Drives
drives="$(lsblk -p | pcregrep -Mv 'sd.[1-9].*\n.*crypt' | grep 'part  $' | awk '{print $1,"("$4")"}')"
[ -z "$drives" ] && exit 1

#Select drive
chosen="$(menu 'Mount' "$drives" 'entry.rasi' | cut -d' ' -f1 | tr -d '└─')"
[ -z "$chosen" ] && exit 1

#Check if the drive is encrypted
if sudo -A blkid | grep "$chosen.*crypto_LUKS"; then
    ddn="$(menu 'Give a name' '' 'entry.rasi')"
    [ -z "$ddn" ] && exit 1
    xterm -background black -foreground white -e "sudo -A cryptsetup open $chosen $ddn"
    chosen="/dev/mapper/$ddn"
fi

#Mount the drive if it is in fstab
sudo -A mount "$chosen" && exit 0

#Select where to mount
find=`find /mnt /run/media ~/ -maxdepth 2 -type d 2>/dev/null`
mp="$(menu 'Where to mount?' "$find" 'entry.rasi')"
[ -z "$mp" ] && exit 1

#If the directory doesn't exist ask to create it
[ ! -d "$mp" ] &&
    [ "$(menu "$mp does not exist. Create it?" 'Yes\nNo' 'entry.rasi')" = "Yes" ] &&
    notify &&
    sudo -A mkdir -p "$mp"

#Mount the drive and send notification
sudo -A mount "$chosen" "$mp" &&
    pgrep -x dunst &&
    notify "$chosen mounted to $mp."
