#!/bin/bash

###########################################################
#
# Dmenu Mount
#
# Written by Dimitri Tzika
# Original by https://github.com/LukeSmithxyz/voidrice/blob/master/.scripts/dmenumount
#
###########################################################

#Check if dmenu is running
pgrep -x dmenu && exit 1

#Drives
drives="$(lsblk -p | pcregrep -Mv 'sd.[1-9].*\n.*crypt' | grep 'part  $' | awk '{print $1,"("$4")"}')"
[ -z "$drives" ] && exit 1

#Select drive
chosen="$(echo "$drives" | dmenu -i -sb "$COLOR1" -p "Mount: Which drive?" | cut -d' ' -f1 | tr -d '└─')"
[ -z "$chosen" ] && exit 1

#Wait for dmenu to close
sleep .2

#Check if the drive is encrypted
if sudo -A blkid | grep "$chosen.*crypto_LUKS"; then
    ddn="$(echo | dmenu -sb "$COLOR1" -p "Give a name:")"
    [ -z "$ddn" ] && exit 1
    xterm -background black -foreground white -e "sudo -A cryptsetup open $chosen $ddn"
    chosen="/dev/mapper/$ddn"
fi

#Mount the drive if it is in fstab
sudo -A mount "$chosen" && exit 0

#Select where to mount
mp="$(find /mnt /run/media ~/ -maxdepth 2 -type d 2>/dev/null | dmenu -i -sb "$COLOR1" -p "Where to mount?")"
[ -z "$mp" ] && exit 1

#Wait for dmenu to close
sleep .2

#If the directory doesn't exist ask to create it
[ ! -d "$mp" ] && [ "$(printf "No\\nYes" | dmenu -b -i -sb "$COLOR1" -p "$mp does not exist. Create it?")" = "Yes" ] && sudo -A mkdir -p "$mp"

#Mount the drive and send notification
sudo -A mount "$chosen" "$mp" && pgrep -x dunst && notify-send "$chosen mounted to $mp."
