#!/bin/bash

# "Favorite" services
servicesToCheck='sshd vsftpd netdata NetworkManager'

{
   
# First message
if [[ "$#" -eq 0 || "$1" == "favorite" ]]; then
    echo "Favorite services"
elif [[ "$1" == "all" ]]; then
    echo "All services"
elif [[ "$1" == "enabled" ]]; then
    echo "Enabled services:"
elif [[ "$1" == "disabled" ]]; then
    echo "Disabled services:"
elif [[ "$1" == "static" ]]; then
    echo "Static services:"
# Error
else
    # Error output for less
    echo "Not valid argument or too many arguments"
    # Error output
    echo "Not valid argument or too many arguments" 1>&2
    exit 1
fi

# Systemd enabled services
systemctl list-unit-files | grep -e 'service' | sed 's/.service//' | sed 's/@//' | tr -s ' ' | while read -r service; do
    serviceName="$(echo "$service" | cut -d ' ' -f 1)"
    serviceStatus="$(echo "$service" | cut -d ' ' -f 2)"
    # Show favorite services
    if [[ ("$#" -eq 0 || "$1" == "favorite") && "$servicesToCheck" =~ $serviceName ]]; then
	printf "%s %s\n" "$serviceName" "$serviceStatus"
    # Show all services
    elif [[ "$1" == "all" ]]; then
	printf "%s %s\n" "$serviceName" "$serviceStatus"
    # Show enabled services
    elif [[ "$1" == "enabled" && "$serviceStatus" == "enabled" ]]; then
	printf "%s\n" "$serviceName"
    # Show disabled services
    elif [[ "$1" == "disabled" && "$serviceStatus" == "disabled" ]]; then
	printf "%s\n" "$serviceName"
    # Show static services
    elif [[ "$1" == "static" && "$serviceStatus" == "static" ]]; then
	printf "%s\n" "$serviceName"
    fi
# Align output and add tab
done  | column -t | sed 's/^/\t/'

} | less 2>/dev/null
