#!/bin/bash

###########################################################
#
# Dmenu Unmount
#
# Written by Dimitri Tzika
# Original by https://github.com/LukeSmithxyz/voidrice/blob/master/.scripts/dmenuumount
#
###########################################################

promptColor="#006677"

#Check if dmenu is running
pgrep -x dmenu && exit 1

#Drives
drives="$(lsblk -p | pcregrep -Me 'part.*\n.*crypt|part.{3}' | grep 'part' | awk '{print $1,"("$4")"}' | tr '├' '└' | egrep -v 'sda')"
[ -z "$drives" ] && exit

#Select drive
chosen="$(echo "$drives" | dmenu -b -i -sb "$promptColor" -p "Unmount: Which drive?" | tr -d '└─' | cut -d' ' -f1)"
[ -z "$chosen" ] && exit

#Check if the drive is encrypted
if blkid | grep "$chosen.*crypto_LUKS"; then
    chosen="$(lsblk -p | pcregrep -Me "$chosen.*\n.*" | grep -o '/dev/mapper/[^ ]*')"
    sudo -A umount "$chosen"
    sudo -A cryptsetup close "$(echo "$chosen" | cut -d/ -f4)"
else
    sudo -A umount "$chosen"
fi && pgrep -x dunst && notify-send "$chosen unmounted."
