#!/bin/bash

###########################################################
#
# Dmenu Unmount
#
# Written by Dimitri Tzika
# Original by https://github.com/LukeSmithxyz/voidrice/blob/master/.scripts/dmenuumount
#
###########################################################

#Drives
drives="$(lsblk -p | pcregrep -Me 'part.*\n.*crypt|part.{3}' | grep 'part' | cut -d' ' -f1 | tr '├' '└')"
[ -z "$drives" ] && exit

#Select drive
chosen="$(echo "$drives" | dmenu -b -i -p "Unmount: Which drive?" | tr -d '└─')"
[ -z "$chosen" ] && exit

#Check if the drive is encrypted
if blkid | grep "$chosen.*crypto_LUKS"; then
    chosen="$(lsblk -p | pcregrep -Me "$chosen.*\n.*" | grep -o '/dev/mapper/[^ ]*')"
    sudo -A umount "$chosen"
    sudo -A cryptsetup close "$(echo "$chosen" | tr -d '/dev/mapper/')"
else
    sudo -A umount "$chosen"
fi && pgrep -x dunst && notify-send "$chosen unmounted."
