#!/bin/bash

source utilities

#Drives
drives="$(lsblk -p | pcregrep -Me 'part.*\n.*crypt|part.{3}' | grep 'part' | awk '{print $1,"("$4")"}' | tr '├' '└' | egrep -v 'sda')"
[ -z "$drives" ] && exit

#Select drive
chosen="$(menu 'Unmount' "$drives" 'entry.rasi' | tr -d '└─' | cut -d' ' -f1)"
[ -z "$chosen" ] && exit

#Check if the drive is encrypted
if blkid | grep "$chosen.*crypto_LUKS"; then
    chosen="$(lsblk -p | pcregrep -Me "$chosen.*\n.*" | grep -o '/dev/mapper/[^ ]*')"
    sudo -A umount "$chosen"
    sudo -A cryptsetup close "$(echo "$chosen" | cut -d/ -f4)"
else
    sudo -A umount "$chosen"
fi && notify "$chosen unmounted."
