#!/bin/bash

###########################################################
#
# VPN???
#
# Written by Dimitri Tzika
#
###########################################################

# Home location
HOME="/home/dimitris"
# VPN config files location
TEI="$HOME/.config/vpn/tei-tux-full-udp.ovpn"
ProtonVPNjp1="$HOME/.config/vpn/jp-free-01.protonvpn.com.tcp.ovpn"
ProtonVPNjp2="$HOME/.config/vpn/jp-free-02.protonvpn.com.tcp.ovpn"
ProtonVPNnl1="$HOME/.config/vpn/nl-free-01.protonvpn.com.tcp.ovpn"
ProtonVPNnl2="$HOME/.config/vpn/nl-free-01.protonvpn.com.tcp.ovpn"
ProtonVPNus1="$HOME/.config/vpn/us-free-01.protonvpn.com.tcp.ovpn"
ProtonVPNus2="$HOME/.config/vpn/us-free-02.protonvpn.com.tcp.ovpn"

# Check if openvpn is running
if [[ $(ps cax | grep openvpn ) > /dev/null ]]; then
    echo "OpenVPN is running" 1>&2; exit 1
fi

if [[ $(whoami) == "root" ]]; then
    case $# in
	# Show option menu for vpn providers
	0) ANS=$(dialog --title "VPN" --menu "Choose a VPN provider" 12 50 2 "TEI" "VPN Service from ATEITHE" "ProtonVPN" "VPN Service from ProtonVPN AG" 3>&2 2>&1 1>&3)
	   clear
	   case $ANS in
	       TEI) sudo openvpn $TEI;;
	       # Show menu option menu for protonvpn server location
	       ProtonVPN) ANS=$(dialog --title "VPN" --menu "Choose server location" 13 50 6 "Japan1" "Server Location" "Japan2" "Server Location" "Netherlands1" "Server Location" "Netherlands2" "Server Location" "United States1" "Server Location" "United States2" "Server Location" 3>&2 2>&1 1>&3)
			  clear
			  case $ANS in
			      Japan1) sudo openvpn $ProtonVPNjp1;;
			      Japan2) sudo openvpn $ProtonVPNjp2;;
			      Netherlands1) sudo openvpn $ProtonVPNnl1;;
			      Netherlands2) sudo openvpn $ProtonVPNnl2;;
			      "United States1") sudo openvpn $ProtonVPNus1;;
			      "United States2") sudo openvpn $ProtonVPNus2;;
			  esac;;
	   esac;;
	# Check argument
	1) case $1 in
	       tei) sudo openvpn $TEI;;
	       protonvpnjp1) sudo openvpn $ProtonVPNjp1;;
	       protonvpnjp2) sudo openvpn $ProtonVPNjp2;;
	       protonvpnnl1) sudo openvpn $ProtonVPNnl1;;
	       protonvpnnl2) sudo openvpn $ProtonVPNnl2;;
	       protonvpnus1) sudo openvpn $ProtonVPNus1;;
	       protonvpnus2) sudo openvpn $ProtonVPNus2;;
	       *) echo "Not valid provider" 1>&2; exit 1;;
	   esac;;
	*) echo "Usage: vpn PROVIDER" 1>&2; exit 1;;
    esac
else
    echo "vpn needs root privileges" 1>&2; exit 1
fi
