#!/bin/bash

###########################################################
#
# VPN made easy
#
###########################################################

location="/home/dimitris/.config/vpn/"
options=""

cd "$location"

for file in *; do
	options+="$file"
	options+="\n"
done

option="$(printf "$options" | dmenu -i -sb "$COLOR1" -p "Which VPN?")"

xterm -background black -foreground white -e "cd $location && sudo openvpn '$option'"
