#!/bin/sh

help="Usage: brightness [OPTION] [MONITOR]
Control brightness via software (xrandr)

Options:
	-i increase brightness 10%
	-d decrease brightness 10%"

if [[ `pgrep brightness | wc -l` != '2' ]]; then
    echo "error: brightness already running" 1>&2
    exit 1
fi

case "$#" in
    2)
	brightness="$(xrandr --verbose | grep Brightness | cut -d' ' -f2 | cut -b 1-3)"
	case "$1" in
	    "-i")
		if [[ $(echo "$brightness < 1.0" | bc) -eq 1 ]]; then
		    for i in {00..99..4}; do
			xrandr --output $2 --brightness "$brightness$i"
		    done
		    brightness="$(echo $brightness + 0.1 | bc)"
		fi
	    notify "Brightness" "$(xrandr --verbose | grep Brightness | cut -d' ' -f2)";;
	    "-d")
		if [[ $(echo "$(xrandr --verbose | grep Brightness | cut -d' ' -f2) > 0.2" | bc) -eq 1 ]]; then
		    brightness="$(echo $brightness - 0.1 | bc)"
		    for i in {99..00..4}; do
			xrandr --output $2 --brightness "$brightness$i"
		    done
		fi
		notify "Brightness" "$(xrandr --verbose | grep Brightness | cut -d' ' -f2)";;
	    *)
		echo "error: not valid argument" 1>&2
		exit 1;;
	esac;;
    *)
	echo "error: no arguments or too many arguments" 1>&2
	exit 1;;
esac

